=== srnpr/srnprframework/SrnprFrameWork/SrnprFile/DragFile/ElementDragXsdFDF.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ElementDragXsdFDF"
    
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/ElementDragXsdFDF.xsd"
    xmlns:mstns="http://tempuri.org/ElementDragXsdFDF.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:element name="elementDragRoot">

		<xs:complexType>

			<xs:sequence>
				<xs:element name="dragList">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dragElement" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>

									<xs:sequence>

										<xs:element name="selectField">
											<xs:complexType>
												<xs:sequence>

													<xs:element name="field" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" use="required" type="xs:long"></xs:attribute>
															<xs:attribute name="header" use="required" type="xs:string"></xs:attribute>
															<xs:attribute name="select" use="required" type="xs:string"></xs:attribute>
															<xs:attribute name="link"  type="xs:string"></xs:attribute>
															<xs:attribute name="defaultShow"  type="xs:string"></xs:attribute>
															<xs:attribute name="showLength"  type="xs:int"></xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="addMenu" minOccurs="0">

											<xs:complexType>
												<xs:sequence>
													<xs:element name="menu" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="functionId" use="required" type="xs:long"></xs:attribute>
															<xs:attribute name="showText" use="required" type="xs:string"></xs:attribute>
															<xs:attribute name="link" use="required" type="xs:string"></xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="groupId" use="required" type="xs:string" ></xs:attribute>
									<xs:attribute name="from" use="required" type="xs:string"></xs:attribute>
									<xs:attribute name="orderBy" use="required" type="xs:string"></xs:attribute>
									<xs:attribute name="where" use="required" type="xs:string"></xs:attribute>
									<xs:attribute name="title" use="required" type="xs:string"></xs:attribute>
									<xs:attribute name="top" use="required" type="xs:long"></xs:attribute>
									<xs:attribute name="functionId" use="required" type="xs:long"></xs:attribute>
									<xs:attribute name="id" use="required" type="xs:long"></xs:attribute>
								</xs:complexType>

							</xs:element>

						</xs:sequence>

					</xs:complexType>

				</xs:element>

			</xs:sequence>

		</xs:complexType>
		<xs:key name="_key_field_id">
			<xs:selector xpath="./dragList/dragElement/selectField/*"></xs:selector>
			<xs:field xpath="@id"></xs:field>
		</xs:key>
	</xs:element>

</xs:schema>

=== srnpr/srnprframework/SrnprFrameWork/SrnprFile/DragFile/ElementDragXmlFDF.xml
<?xml version="1.0" encoding="utf-8" ?>
<elementDragRoot  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				  xsi:schemaLocation="http://SrnprFrameWork/SrnprFile/ConfigFile ElementDragXsdFDF.xsd" >
	<dragList>
		<dragElement id="1" groupId="1" from="Ope_AgentFilterList" orderBy="CreateDate desc"
					 where=" ExecNotesID='{0}'" title="渠道筛选工单"  functionId=""  top="5" >
			<selectField>
				<field id="1001" header="创建人" select="CrateOperator"/>
				<field id="1002" header="审批人" select="ExecNotesID"/>
			</selectField>
			<addMenu>
				<menu functionId="" showText="创建渠道筛选工单" link="/Ope/Filter/FilterPro.aspx"/>
			</addMenu>
		</dragElement>
		<dragElement id="2" groupId="1" from="Ope_AgentFilterList" orderBy="CreateDate desc"
					 where=" ExecNotesID='{0}'" title="渠道筛选工单"  functionId=""  top="5" >
			<selectField>
				<field id="1003" header="创建人" select="CrateOperator"/>
				<field id="1004" header="审批人" select="ExecNotesID"/>
			</selectField>
			<addMenu>
				<menu functionId="" showText="创建渠道筛选工单" link="/Ope/Filter/FilterPro.aspx"/>
			</addMenu>
		</dragElement>

	</dragList>

</elementDragRoot>
